name: shalashaska
channels:
  - defaults
dependencies:
  - unidecode
  - django-cors-headers
  - osmnx
  - python-dotenv
  - python
  - django
  - drf-yasg
  - djangorestframework
  - geopy